### ISSUE TITLE
"kind" property deprecated

### ISSUE THREAD

**Issue by beautyfree** [tommoor/slate-md-serializer#4]
Need to change "kind" to "object" for new versions of slate:
![image](https://user-images.githubusercontent.com/656531/36138628-343b7408-10ab-11e8-9db7-d70efcb4aa52.png)

**Comment by tommoor** [comment]
Yep thanks for filing. I’ll be updating for the new Slate soon

Sent from Astro <https://www.helloastro.com> for iOS


On Feb 12, 2018 at 23:48, Alexey Elizarov <notifications@github.com> wrote:


Need to change "kind" to "object" for new versions of slate:
[image: image]
<https://user-images.githubusercontent.com/656531/36138628-343b7408-10ab-11e8-9db7-d70efcb4aa52.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tommoor/slate-md-serializer/issues/4>, or mute the
thread
